name: Fetch Pixiv Artwork

on:
  workflow_dispatch:
    inputs:
      artwork_id:
        description: 'Pixiv artwork ID'
        required: true
        type: string

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Pixiv fetcher
        env:
          PIXIV_REFRESH_TOKEN: ${{ secrets.PIXIV_REFRESH_TOKEN }}
        run: python src/fetch_pixiv.py ${{ github.event.inputs.artwork_id }}
        
      - name: Generate Markdown
        run: |
          # 创建内容目录
          mkdir -p src/content/pixiv
          
          # 读取元数据
          ARTWORK_ID=${{ github.event.inputs.artwork_id }}
          METADATA=$(cat artworks/$ARTWORK_ID/metadata.json)
          
          # 获取图片列表
          IMAGES=$(ls artworks/$ARTWORK_ID/*.jpg | sed 's/^/"/;s/$/"/' | tr '\n' ',' | sed 's/,$//')
          
          # 更新元数据中的图片路径
          UPDATED_METADATA=$(echo $METADATA | jq --arg images "[$IMAGES]" '.images = ($images | fromjson)')
          
          # 保存为 JSON 文件
          echo $UPDATED_METADATA > src/content/pixiv/$ARTWORK_ID.json
        
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add artworks/ src/content/pixiv/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Add artwork ${{ github.event.inputs.artwork_id }}" && git push) 