name: Fetch Pixiv Artwork

on:
  workflow_dispatch:
    inputs:
      artwork_id:
        description: 'Pixiv artwork ID'
        required: true
        type: string
        default: ''
      exclude_images:
        description: '要排除的图片索引（用逗号分隔，从0开始），例如：0,2,3 表示排除第1、3、4张图片'
        required: false
        type: string
        default: ''

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pixivpy3==3.7.0
          pip install python-dotenv==1.0.1
          pip install requests==2.31.0
          pip install beautifulsoup4==4.12.3
          pip install Pillow==10.2.0
          
      - name: Check directory structure
        run: |
          echo "Current directory structure:"
          ls -la
          echo "Creating directories if they don't exist..."
          mkdir -p src/content/images/pixiv
          mkdir -p src/content/pixiv
          
      - name: Run fetch script
        run: python fetch_pixiv.py ${{ github.event.inputs.artwork_id }} "${{ github.event.inputs.exclude_images }}"
        env:
          PIXIV_REFRESH_TOKEN: ${{ secrets.PIXIV_REFRESH_TOKEN }}
          
      - name: Check downloaded files
        run: |
          echo "Checking downloaded files:"
          ls -la src/content/images/pixiv
          ls -la src/content/pixiv
          echo "Checking artworks.json:"
          cat src/content/pixiv/artworks.json
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/content/images/pixiv src/content/pixiv
          git status
          git commit -m "chore: update pixiv artwork ${{ github.event.inputs.artwork_id }}" || exit 0
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} 