name: Fetch Pixiv Artwork

on:
  workflow_dispatch:
    inputs:
      artwork_id:
        description: 'Pixiv artwork ID'
        required: true
        type: string

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Check directories before fetching
        run: |
          mkdir -p artworks
          mkdir -p src/content/pixiv
          ls -la
          pwd
          
      - name: Run Pixiv fetcher
        env:
          PIXIV_REFRESH_TOKEN: ${{ secrets.PIXIV_REFRESH_TOKEN }}
        run: |
          python fetch_pixiv.py ${{ github.event.inputs.artwork_id }}
          echo "Fetching completed, checking directory structure:"
          ls -la artworks
          ls -la artworks/${{ github.event.inputs.artwork_id }}
        
      - name: Generate Content Collection
        run: |
          # 复制元数据
          ARTWORK_ID=${{ github.event.inputs.artwork_id }}
          echo "Copying metadata from: artworks/$ARTWORK_ID/metadata.json"
          echo "Target path: src/content/pixiv/$ARTWORK_ID.json"
          cp artworks/$ARTWORK_ID/metadata.json src/content/pixiv/$ARTWORK_ID.json
        
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add artworks/ src/content/pixiv/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Add artwork ${{ github.event.inputs.artwork_id }}" && git push) 